### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by Panquesito7** [loftwah/linux-for-pirates#10]
Title says it all. :)

**Comment by loftwah** [comment]
You are fantastic. Thank you for getting involved. I'll sort this side of the project out soon so issues and PRs can be adequately managed with GitHub Actions. 🙇‍♂️🌟

**Comment by Panquesito7** [comment]
Amazing, thanks! If you need any help with this, let me know. 🙂

**Comment by loftwah** [comment]
I'll get to it over the weekend if I haven't beforehand. Feel free to nudge me if I've forgotten.

**Comment by loftwah** [comment]
This one is sorted. If you can have a look and let me know if you think I could have done anything better that would be awesome.

**Comment by loftwah** [comment]
Didn't mean to close this :)

**Comment by Panquesito7** [comment]
I'll create a PR soon to convert them to [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). I hope that sounds good. :)

**Comment by loftwah** [comment]
Oh cool thanks, I saw that but I didn't have time to update them yet.

**Comment by loftwah** [comment]
Which issue should we keep open?

**Comment by Panquesito7** [comment]
> Which issue should we keep open?

Not 100% sure. Feel free to choose whatever you think is best. 🙂

**Comment by loftwah** [comment]
I'm going to close this job because we technically already have the templates and the other issue is to change them into the correct format.
