### ISSUE TITLE
Use github issue yaml syntax

### ISSUE THREAD

**Issue by suitupstan** [loftwah/linux-for-pirates#17]
Yaml issues are like forms and much more accessible to contributors who don't make much experience

**Comment by Panquesito7** [comment]
Already specified in #10, I guess.
By the way, I'm working on this. 🙂

**Comment by suitupstan** [comment]
Awesome @Panquesito7 - maybe even change the titles of the issues if the goal changes 🤔

**Comment by loftwah** [comment]
This is good. I saw this but couldn't figure out how to do it. I think the Markdown version is more straightforward but I will merge anything that fixes this, or eventually, I'll fix it myself.
