### ISSUE TITLE
Remove author from artwork

### ISSUE THREAD

**Issue by loftwah** [loftwah/linux-for-pirates#21]
Ahoy matey!

Before ye create a new issue, please make sure to search through the existing issues to see if your problem has already been addressed.

#### Issue Description:

Artwork has author name and this will be written by multiple people so no need for a name.

#### Page number and chapter:

[Include the page number and chapter where the issue is located]

#### Expected result:

[Describe what ye expected to happen]

#### Actual result:

[Describe what actually happened]

#### Additional context:

[Include any additional information that might be relevant to the issue]

Thanks for bringing this issue to our attention. We'll do our best to address it as soon as we can.

Yarrrr!

**Comment by ibilalkayy** [comment]
Should I remove a picture and the whole description of the author also? What should be removed because the first is the heading, then a banner with your photo, and then your description.

**Comment by loftwah** [comment]
If I miss anything, we can fix it. It shouldn't need to display any author.

**Comment by loftwah** [comment]
These have been fixed.
