### ISSUE TITLE
Adding Linux commands

### ISSUE THREAD

**Issue by Ayaan49** [loftwah/linux-for-pirates#27]
Hello sir, since Linux for Pirates is for learning about the Linux operating system then why doesn't it have anything about the linux commands? Don't you think it would be a good idea to include the linux commands in this repo as well? Please let me know if my suggestion is valid or not.

**Comment by loftwah** [comment]
It does have some [here](https://loftwah.github.io/linux-for-pirates/#handybilly), and the [exercises](https://loftwah.github.io/linux-for-pirates/#initiation) already go over them quite extensively. We plan to cover them further and will be adding a lot more about Linux and the different commands you would expect to find.
