### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by loftwah** [loftwah/linux-for-pirates#31]
Ahoy matey!

Before ye create a new issue, please make sure to search through the existing issues to see if your problem has already been addressed.

#### Issue Description:

The last merge broke some images and we need to fix them.

#### Page number and chapter:

Multiple. Will need to find them and resolve them.

#### Expected result:

Fix the broken images.

#### Additional context:

This is a good first issue

Thanks for bringing this issue to our attention. We'll do our best to address it as soon as we can.

Yarrrr!

**Comment by KlausMikhaelson** [comment]
Hey @loftwah can I work on this issue ?

**Comment by loftwah** [comment]
Absolutely! I'll assign it to you. I haven't set anything up for this yet formally, but I can leave it with you for the week.

**Comment by loftwah** [comment]
Welcome to the project!

**Comment by KlausMikhaelson** [comment]
great!, I did found 1 but ig I gotta check it out nicely to find the others !
will update as soon as I find them !
Thank you !

**Comment by loftwah** [comment]
This has been unassigned. I will complete the task.

**Comment by KlausMikhaelson** [comment]
uhhh sorry I forgot about it
will try to find other issues to contribute to

**Comment by loftwah** [comment]
Nevermind, I don't think it was you I think we fixed it unintentionally without you. Also never a problem here :) that is what this project is about. It is a very friendly and forgiving environment. Nothing urgent.

**Comment by KlausMikhaelson** [comment]
Ooo okay, ig I am gonna create an extension that can remind me of the assigned issues every morning at a certain time, bcoz this is something that I do really often
Thank you will try to contribute to other issues !

**Comment by loftwah** [comment]
We all do it, don't sweat it.
