### ISSUE TITLE
Fix broken link to issues page in the contributing giude 

### ISSUE THREAD

**Issue by opeolluwa** [loftwah/linux-for-pirates#7]
The Issue page link [https://github.com/YOUR-USERNAME/linux-for-pirates/issues](https://github.com/YOUR-USERNAME/linux-for-pirates/issues) is broken

**Comment by loftwah** [comment]
You are fantastic. Thank you for getting involved. I'll sort this side of the project out soon so issues and PRs can be adequately managed with GitHub Actions. 🙇‍♂️🌟

**Comment by opeolluwa** [comment]
Resolved
